name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar las credenciales de AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # 3. Instalar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # 4. Inicializar Terraform
      - name: Initialize Terraform
        run: terraform init

      # 5. Planificar los cambios
      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -no-color > plan_output.txt
          if grep -q "No changes. Infrastructure is up-to-date." plan_output.txt; then
            echo "No changes detected in the plan. Exiting gracefully."
            echo "no_changes=true" >> $GITHUB_ENV
            exit 0
          else
            echo "no_changes=false" >> $GITHUB_ENV
          fi

      # 6. Aplicar los cambios
      - name: Terraform Apply
        if: env.no_changes != 'true'
        run: terraform apply -auto-approve