name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar las credenciales de AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # 3. Instalar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # 4. Inicializar Terraform
      - name: Terraform Init
        run: terraform init

      # 5. Detectar y Importar Recursos Existentes
      - name: Detect Existing Resources
        run: |
          # Detect if resources exist and import them into Terraform state
          for resource in "deployment/app1" "service/app1-service" "deployment/app2" "service/app2-service"; do
            if kubectl get $resource -n default; then
              echo "Resource $resource exists, importing to Terraform..."
              terraform import kubernetes_manifest.${resource//\//_} default/$(basename $resource)
            else
              echo "Resource $resource does not exist, skipping import."
            fi
          done

      # 6. Planificar los cambios
      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -no-color > plan_output.txt
          if grep -q "No changes. Infrastructure is up-to-date." plan_output.txt; then
            echo "No changes detected in the plan. Exiting gracefully."
            echo "no_changes=true" >> $GITHUB_ENV
            exit 0
          else
            echo "no_changes=false" >> $GITHUB_ENV
          fi

      # 7. Aplicar los cambios
      - name: Terraform Apply
        if: env.no_changes != 'true'
        run: terraform apply -auto-approve